version: '3.7'

services:
  op_python2:
    hostname: octoprint_python2
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile.python2
    ports:
      - "${OP_PYTHON2_PORT-5002}:5000"
    volumes:
     - ./:/app
    environment:
        DEBUG: 'True'
        JANUS_SERVER: 'janus'
    depends_on:
      - janus
    command: bash -c "sleep 11111111111"

  op:
    hostname: octoprint
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile.python3
    ports:
      - "${OP_PYTHON3_PORT-5003}:5000"
    volumes:
     - ./:/app
    environment:
        DEBUG: 'True'
        PRECONFIGURED_WEBCAMS: '{"janus_server": "janus", "webcams": [{"name": "video", "is_primary_camera": true, "is_nozzle_camera": false, "stream_mode": "h264_transcode", "stream_id": 1, "flipV": true, "flipH": false, "rotation": 270, "streamRatio": "4:3"}, {"name": "nozzle", "is_primary_camera": false, "is_nozzle_camera": true, "stream_mode": "h264_transcode", "stream_id": 3, "flipV": false, "flipH": true, "rotation": 0, "streamRatio": "16:9"}]}'
    depends_on:
      - janus
    command: bash -c "sleep 11111111111"

  janus:
    hostname: janus
    restart: unless-stopped
    image: thespaghettidetective/janus:ubuntu-1.7
    #command: sh -c "/opt/janus/bin/janus --stun-server=stun.l.google.com:19302"
    command: sh -c "/opt/janus/bin/janus"
  mjpeg:
    hostname: mjpeg
    restart: unless-stopped
    image: thespaghettidetective/mjpg-streamer
    ports:
      - "${MJPEG_PORT-8080}:8080"
    command: sh -c "/mjpg-streamer/mjpg_streamer -o '/mjpg-streamer/output_http.so -w /mjpg-streamer/www' -i '/mjpg-streamer/input_file.so -f /mjpg-streamer/jpgs -e -d 1'"

  video:
    restart: unless-stopped
    image: thespaghettidetective/ffmpeg:ubuntu-1.1
    command: bash -c "ffmpeg -f concat -re -i list.txt -c copy -bsf dump_extra -an -f rtp rtp://janus:17732?pkt_size=1300"
  video2:
    restart: unless-stopped
    image: thespaghettidetective/ffmpeg:ubuntu-1.1
    command: bash -c "ffmpeg -f concat -re -i list2.txt -c copy -bsf dump_extra -an -f rtp rtp://janus:17735?pkt_size=1300"
