api:
  key: D72ED4FE5E9C48D4AFBEBE8561FA94D6
devel:
  cache:
    enabled: false
    preemptive: false
  stylesheet: css
  webassets:
    bundle: false
    clean_on_startup: true
    minify: true
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1698671700
      _important:
        read_until: 1698310200
      _octopi:
        read_until: 1684929600
      _plugins:
        read_until: 1701907200
      _releases:
        read_until: 1696862700
  classicwebcam:
    _config_version: 1
    flipH: true
    rotate90: true
    snapshot: http://mjpeg:8080/?action=snapshot
    stream: http://localhost:8080/?action=stream
  discovery:
    upnpUuid: 6c0a6d28-453f-4a42-836c-40e57dca0385
  errortracking:
    unique_id: a6dd8216-f4eb-4ea1-9d17-9dfa01d2ab4a
  gcodeviewer:
    _config_version: 1
  multicam:
    _config_version: 3
    multicam_profiles:
    - URL: http://192.168.0.248:8080/?action=stream
      flipH: null
      flipV: null
      isButtonEnabled: 'true'
      name: Default
      rotate90: null
      snapshot: http://192.168.0.248:8080/?action=snapshot
      streamRatio: '16:9'
    - URL: http://localhost:8080/?action=stream
      flipH: false
      flipV: false
      isButtonEnabled: true
      name: Webcam 1
      rotate90: false
      snapshot: http://mjpeg:8080/?action=snapshot
      streamRatio: '16:9'
  obico:
    auth_token: f2c9e57545268582c8de
    endpoint_prefix: https://app-stg.obico.io
    nozzle_camera: null
    sentry_opt: in
    tsd_migrated: confirmed
    webcams:
    - is_primary_camera: true
      name: multicam/Default
      resolution: medium
      target_fps: '10'
    - is_primary_camera: false
      name: multicam/Webcam 1
      resolution: medium
      target_fps: '5'
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: f559f7c2-42db-4d95-9ad8-a5207e8b5780
  virtual_printer:
    _config_version: 1
    enabled: true
    movementSpeed:
      e: 300
      x: 6000
      y: 6000
      z: 200
    okWithLinenumber: false
    repetierStyleResends: false
    sendWait: false
serial:
  autoconnect: true
  log: true
server:
  firstRun: false
  onlineCheck:
    enabled: false
  pluginBlacklist:
    enabled: false
  secretKey: DHqhKnZ3h93vojEA4b5QWfRiSe28PH1r
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
webcam:
  ffmpeg: /usr/bin/avconv
